/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/angular2-tinymce.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '../../src/angular2-tinymce.default';
class TinymceModuleInjector extends import0.ɵNgModuleInjector<import1.TinymceModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _TinymceModule_4:import1.TinymceModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __ɵi_6:import3.ɵi;
  __FormBuilder_7:import3.FormBuilder;
  __TINYMCE_CONFIG_8:import4.TinymceDefaultOptions;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  get _FormBuilder_7():import3.FormBuilder {
    if ((this.__FormBuilder_7 == null)) { (this.__FormBuilder_7 = new import3.FormBuilder()); }
    return this.__FormBuilder_7;
  }
  get _TINYMCE_CONFIG_8():import4.TinymceDefaultOptions {
    if ((this.__TINYMCE_CONFIG_8 == null)) { (this.__TINYMCE_CONFIG_8 = new import4.TinymceDefaultOptions()); }
    return this.__TINYMCE_CONFIG_8;
  }
  createInternal():import1.TinymceModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._TinymceModule_4 = new import1.TinymceModule();
    return this._TinymceModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import1.TinymceModule)) { return this._TinymceModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_7; }
    if ((token === 'TINYMCE_CONFIG')) { return this._TINYMCE_CONFIG_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TinymceModuleNgFactory:import0.NgModuleFactory<import1.TinymceModule> = new import0.NgModuleFactory<any>(TinymceModuleInjector,import1.TinymceModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovc2l0ZXMvb3duL2FuZ3VsYXIyLXRpbnltY2UtMi9zcmMvYW5ndWxhcjItdGlueW1jZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovc2l0ZXMvb3duL2FuZ3VsYXIyLXRpbnltY2UtMi9zcmMvYW5ndWxhcjItdGlueW1jZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
