/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/angular2-tinymce.module';
import * as import2 from '@angular/common';
class TinymceModuleInjector extends import0.ɵNgModuleInjector<import1.TinymceModule> {
  _CommonModule_0:import2.CommonModule;
  _TinymceModule_1:import1.TinymceModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.TinymceModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._TinymceModule_1 = new import1.TinymceModule();
    return this._TinymceModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.TinymceModule)) { return this._TinymceModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TinymceModuleNgFactory:import0.NgModuleFactory<import1.TinymceModule> = new import0.NgModuleFactory<any>(TinymceModuleInjector,import1.TinymceModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovc2l0ZXMvb3duL2FuZ3VsYXIyLXRpbnltY2UtMi9zcmMvYW5ndWxhcjItdGlueW1jZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovc2l0ZXMvb3duL2FuZ3VsYXIyLXRpbnltY2UtMi9zcmMvYW5ndWxhcjItdGlueW1jZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
