/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/angular2-tinymce.component';
import * as i2 from '@angular/forms';
const styles_TinymceComponent:any[] = ([] as any[]);
export const RenderType_TinymceComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TinymceComponent,data:{}});
export function View_TinymceComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),0,'div',([] as any[]),
      [[8,'id',0]],(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (_ck,_v) => {
        var _co:i1.TinymceComponent = _v.component;
        const currVal_0:any = i0.ɵinlineInterpolate(1,'',_co.elementId,'');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_TinymceComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),2,'app-tinymce',
      ([] as any[]),(null as any),(null as any),(null as any),View_TinymceComponent_0,
      RenderType_TinymceComponent)),i0.ɵprd(5120,(null as any),i2.NG_VALUE_ACCESSOR,
      (p0_0:any) => {
        return [p0_0];
      },[i1.TinymceComponent]),i0.ɵdid(2,4374528,(null as any),0,i1.TinymceComponent,
      [i0.NgZone,'TINYMCE_CONFIG'],(null as any),(null as any))],(null as any),(null as any));
}
export const TinymceComponentNgFactory:i0.ComponentFactory<i1.TinymceComponent> = i0.ɵccf('app-tinymce',
    i1.TinymceComponent,View_TinymceComponent_Host_0,{config:'config'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyLXRpbnltY2Uvc3JjL2FuZ3VsYXIyLXRpbnltY2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cy5UaW55bWNlQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9BZG1pbmlzdHJhdG9yL0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQudHMuVGlueW1jZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgaWQ9XCJ7e2VsZW1lbnRJZH19XCI+PC9kaXY+IiwiPGFwcC10aW55bWNlPjwvYXBwLXRpbnltY2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7OztRQUFLO1FBQUwsV0FBSyxTQUFMOzs7O29CQ0FBO01BQUE7aUNBQUE7TUFBQTtRQUFBO01BQUEsZ0NBQUE7TUFBQTs7OyJ9
