/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/angular2-tinymce.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '../../src/angular2-tinymce.default';
export const TinymceModuleNgFactory:i0.NgModuleFactory<i1.TinymceModule> = i0.ɵcmf(i1.TinymceModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i3.FormBuilder,i3.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,'TINYMCE_CONFIG',i4.TinymceDefaultOptions,([] as any[])),i0.ɵmpd(512,
              i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,
              ([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i3.ReactiveFormsModule,i3.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i1.TinymceModule,i1.TinymceModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyLXRpbnltY2Uvc3JjL2FuZ3VsYXIyLXRpbnltY2UubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
