/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/angular2-tinymce.component';
import * as import2 from '@angular/forms';
const styles_TinymceComponent:any[] = ([] as any[]);
export const RenderType_TinymceComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TinymceComponent,
  data: {}
}
);
export function View_TinymceComponent_0(l:any):import0.ɵViewDefinition {
      return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),[[
        8,
        'id',
        0
      ]
  ],(null as any),(null as any),(null as any),(null as any)))],(null as any),(ck,v) => {
    var co:import1.TinymceComponent = v.component;
    const currVal_0:any = import0.ɵinlineInterpolate(1,'',co.elementId,'');
    ck(v,0,0,currVal_0);
  });
}
function View_TinymceComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-tinymce',([] as any[]),(null as any),(null as any),(null as any),View_TinymceComponent_0,RenderType_TinymceComponent)),
    import0.ɵdid(4374528,(null as any),0,import1.TinymceComponent,[
      import0.NgZone,
      'TINYMCE_CONFIG'
    ]
    ,(null as any),(null as any)),
    import0.ɵprd(5120,(null as any),import2.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import1.TinymceComponent])
  ]
  ,(null as any),(null as any));
}
export const TinymceComponentNgFactory:import0.ComponentFactory<import1.TinymceComponent> = import0.ɵccf('app-tinymce',import1.TinymceComponent,View_TinymceComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWthbXJhbi9SZXBvc2l0b3JpZXMvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ta2FtcmFuL1JlcG9zaXRvcmllcy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvbWthbXJhbi9SZXBvc2l0b3JpZXMvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQudHMuVGlueW1jZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vaG9tZS9ta2FtcmFuL1JlcG9zaXRvcmllcy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cy5UaW55bWNlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBpZD1cInt7ZWxlbWVudElkfX1cIj48L2Rpdj4iLCI8YXBwLXRpbnltY2U+PC9hcHAtdGlueW1jZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZCQ0FBO1FBQUE7UUFBQTtRQUFBO01BQUE7RUFBQTs7SUFBSztJQUFMLFNBQUssU0FBTDs7Ozs7SUNBQTtnQkFBQTs7TUFBQTtJQUFBO0tBQUE7Z0JBQUE7TUFBQTtJQUFBOzs7OyJ9
